@extends('layouts.admin')

@section('title', 'Edit ' . $device->account_number)

@section('content')
<div class="flex items-center gap-2 text-[12.5px] text-[#9AA0AA] mb-4">
    <a href="{{ route('admin.devices.index') }}" class="text-[#787E88] hover:text-brand">Devices</a>
    <span>/</span>
    <a href="{{ route('admin.devices.show', $device) }}" class="text-[#787E88] hover:text-brand tnum">{{ $device->account_number }}</a>
    <span>/</span>
    <span class="text-[#1A1D23]">Edit</span>
</div>

<h1 class="text-[24px] font-bold tracking-[-0.025em] mb-6">Edit device</h1>

<div class="max-w-2xl bg-white border border-[#E9EBEF] rounded-[14px] shadow-[0_1px_2px_rgba(16,20,28,.03)] p-6">
    @if ($errors->any())
        <div class="mb-4 px-4 py-3 rounded-lg bg-[#FBEAE8] border border-[#F1C9C4] text-[13px] text-[#B23A30]">{{ $errors->first() }}</div>
    @endif

    <form method="POST" action="{{ route('admin.devices.update', $device) }}" class="space-y-4">
        @csrf
        @method('PATCH')
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
                <label class="block text-[12.5px] font-medium text-[#4A4F58] mb-1.5">Device name</label>
                <input name="name" value="{{ old('name', $device->name) }}" class="w-full h-10 border border-[#E4E6EB] bg-[#F7F8FA] rounded-lg px-3 text-[13px] outline-none focus:border-brand">
            </div>
            <div>
                <label class="block text-[12.5px] font-medium text-[#4A4F58] mb-1.5">Model</label>
                <input name="model" value="{{ old('model', $device->model) }}" class="w-full h-10 border border-[#E4E6EB] bg-[#F7F8FA] rounded-lg px-3 text-[13px] outline-none focus:border-brand">
            </div>
            <div>
                <label class="block text-[12.5px] font-medium text-[#4A4F58] mb-1.5">Selling price <span class="text-[#C2453D]">*</span></label>
                <div class="relative">
                    <span class="absolute left-3 top-1/2 -translate-y-1/2 text-[12px] text-[#9AA0AA]">{{ trim(currency_prefix()) }}</span>
                    <input name="price" type="number" step="0.01" min="0" value="{{ old('price', $device->price) }}" required
                           class="w-full h-10 border border-[#E4E6EB] bg-[#F7F8FA] rounded-lg pl-12 pr-3 text-[13px] tnum outline-none focus:border-brand">
                </div>
            </div>
            <div>
                <label class="block text-[12.5px] font-medium text-[#4A4F58] mb-1.5">Serial number <span class="text-[#C2453D]">*</span></label>
                <input name="serial" value="{{ old('serial', $device->serial) }}" required class="w-full h-10 border border-[#E4E6EB] bg-[#F7F8FA] rounded-lg px-3 text-[13px] tnum outline-none focus:border-brand">
            </div>
            <div>
                <label class="block text-[12.5px] font-medium text-[#4A4F58] mb-1.5">Account number</label>
                <div class="w-full h-10 border border-[#E4E6EB] bg-[#EEF0F3] rounded-lg px-3 text-[13px] tnum text-[#565b64] flex items-center">{{ $device->account_number }}</div>
                <p class="text-[11px] text-[#9AA0AA] mt-1">Fixed for the life of the device — the machine stores this copy too.</p>
            </div>
        </div>

        <div class="pt-2 border-t border-[#EEF0F3]">
            <div class="flex items-center gap-2 text-[13px] font-semibold text-[#8A2B23] mt-3 mb-1"><x-icon name="shield" class="w-4 h-4" /> Recovery vault</div>
            <p class="text-[11.5px] text-[#9AA0AA] mb-3">Leave blank to keep the current values. Encrypted at rest.</p>
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                    <label class="block text-[12.5px] font-medium text-[#4A4F58] mb-1.5">BIOS password</label>
                    <x-password-input name="bios_password" autocomplete="off" placeholder="{{ $device->bios_password ? '•••••••• (set)' : 'Not set' }}" class="tnum" />
                </div>
                <div>
                    <label class="block text-[12.5px] font-medium text-[#4A4F58] mb-1.5">BitLocker recovery key</label>
                    <x-password-input name="recovery_key" autocomplete="off" placeholder="{{ $device->recovery_key ? '•••••••• (set)' : 'Not set' }}" class="tnum" />
                </div>
                <div class="sm:col-span-2">
                    <label class="block text-[12.5px] font-medium text-[#4A4F58] mb-1.5">Uninstall code <span class="text-[#9AA0AA] font-normal">(from the device app)</span></label>
                    <input name="uninstall_code" value="{{ old('uninstall_code', $device->uninstall_code) }}" autocomplete="off" placeholder="Generated by the offline app at install"
                           class="w-full h-10 border border-[#E4E6EB] bg-[#F7F8FA] rounded-lg px-3 text-[13px] tnum outline-none focus:border-brand">
                    <p class="text-[11px] text-[#9AA0AA] mt-1">Generated by the offline lock client on the device. Recorded here so you can authorize uninstalling when the plan completes.</p>
                </div>
            </div>
        </div>

        <div class="flex items-center gap-2 pt-1">
            <button type="submit" class="h-10 px-4 rounded-lg bg-brand text-white text-[13px] font-semibold shadow-[0_1px_3px_rgba(75,69,199,.35)]">Save changes</button>
            <a href="{{ route('admin.devices.show', $device) }}" class="h-10 px-4 flex items-center rounded-lg border border-[#E4E6EB] bg-white text-[13px] font-medium text-[#4A4F58]">Cancel</a>
        </div>
    </form>
</div>
@endsection
